library:
  source-dirs: src
tests:
  hask-monomi-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-monomi
    - Hspec
copyright: fouche
maintainer: fosco.loregian@gmail.com
dependencies:
- base >= 4.7 && < 5
- List
name: hask-monomi
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: fouche
github: tetrapharmakon/hask-monomi
license: BSD3
executables:
  hask-monomi-exe:
    source-dirs: src
    main: Multinomiala.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-monomi
description: Please see the README on GitHub at <https://github.com/tetrapharmakon/hask-monomi#readme>
